language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

install:
  - "cpanm -n Test::More Test::Simple Test::Harness Test::Pod::Coverage"
  - "cpanm -n Email::MIME::Encodings Email::MIME::ContentType"
  - "cpanm -n Email::Address Email::MessageID Email::Simple"
  - "cpanm -n --installdeps ."

notifications:
  email: false
